Fix path to csv default class
Previously failed with

Traceback (most recent call last):
        7: from /usr/local/bundle/gems/commander-4.4.7/lib/commander/import.rb:5:in `block in <top (required)>'
        6: from /usr/local/bundle/gems/commander-4.4.7/lib/commander/delegates.rb:15:in `run!'
        5: from /usr/local/bundle/gems/commander-4.4.7/lib/commander/runner.rb:68:in `run!'
        4: from /usr/local/bundle/gems/commander-4.4.7/lib/commander/runner.rb:446:in `run_active_command'
        3: from /usr/local/bundle/gems/commander-4.4.7/lib/commander/command.rb:153:in `run'
        2: from /usr/local/bundle/gems/commander-4.4.7/lib/commander/command.rb:182:in `call'
        1: from ./import:131:in `block (2 levels) in <main>'
/usr/local/bundle/gems/commander-4.4.7/lib/commander/user_interaction.rb:359:in `method_missing': undefined method `new' for F2ynab::Import::Csv:Module (NoMethodError)